export const resources = [
  {
    name: "customers",
    list: "/customers",
    create: "/customers/create",
    edit: "/customers/edit/:id",
    show: "/customers/show/:id",
    meta: { canDelete: true },
  },
  {
    name: "orders",
    list: "/orders",
    create: "/orders/external/create",
    edit: "/orders/edit/:id",
    show: "/orders/show/:id",
    meta: { canDelete: true },
  },
  { name: "cnBatches", list: "/cn-batches" },
  { name: "cnPackages", list: "/china-warehouse" },
  { name: "vnWarehouse", list: "/vietnam-warehouse" },
  { name: "paymentVouchers", list: "/payment-vouchers", show: "/payment-vouchers/:id" },
  { name: "invoices", list: "/invoices", create: "/invoices/create", show: "/invoices/:id" },
  { name: "revenueReport", list: "/revenue-report" },
  { name: "shippingRates", list: "/shipping-rates" },
  { name: "exchangeRates", list: "/exchange-rates" },
  { name: "employees", list: "/employees" },
  { name: "shippingQueue", list: "/shipping/queue", create: "/shipping/create" },
  { name: "shippingTasks", list: "/shipping/tasks", show: "/shipping/tasks/:id" },
  { name: "exportSlips", list: "/shipping/slips", show: "/shipping/slips/:id" },
  { name: "users" },
];
